name: CI Pipeline

on:
  push:
    branches: 
      - master
      - "feature/**"
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet nohup run
      
    - name: Install test dependencies
      run: |
        dotnet add br.com.fiap.alert.test/br.com.fiap.alert.test.csproj package Microsoft.NET.Test.Sdk
        dotnet add br.com.fiap.alert.test/br.com.fiap.alert.test.csproj package xunit
        dotnet add br.com.fiap.alert.test/br.com.fiap.alert.test.csproj package xunit.runner.visualstudio
        dotnet add br.com.fiap.alert.test/br.com.fiap.alert.test.csproj package coverlet.collector
      
    - name: Test
      run: cd br.com.fiap.alert.test && dotnet test --configuration Release --verbosity normal
      
    - name: Run API
      run: |
        cd br.com.fiap.alert.api
        dotnet run &
        sleep 10